spring:
  datasource:
    url: jdbc:mysql://192.249.29.56:3306/sign
    username: testuser
    password: rj7783208232
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
